name: deploy
on:
  push:
    branches: [ main ]  
jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: execute deployment script
      uses: appleboy/ssh-action@v0.1.2
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}        
        script: |
          pushd ~/emprendesg_svr
          ./deploy.sh
